### ISSUE TITLE
Expose MagazineLayout.Default enum as public

### ISSUE THREAD

**Issue by diegorozen** [airbnb/MagazineLayout#10]
While I was building an RxSwift extension for MagazineLayout (which can be discussed in a different topic), I needed to provide sensible defaults for the cases when a forwarding delegate was not defined. Those defaults have already being defined by the lib in MagazineLayout.Default, but they are not visible outside the library.

Since that enum doesn't expose any internal implementation details, it would be helpful to mark it as public

Thanks,
Diego

**Comment by bryankeller** [comment]
@diegorozen thanks a bunch for making an RxSwift extension. I think the change you're proposing makes sense. I'll get a PR up soon to make the change, unless you beat me to it 🙂
