### ISSUE TITLE
Respect safe area

### ISSUE THREAD

**Issue by fruitcoder** [airbnb/MagazineLayout#13]
Currently the layout only looks at the collection view's `contentInset` but ignores the safe area. The result is that the cells are inset to the right which caused them to be cutoff (on the right side). See 

<img width="821" alt="screenshot 2019-01-08 at 16 58 12" src="https://user-images.githubusercontent.com/5515849/50845600-8bd70b80-136d-11e9-9180-e486db9115cc.png">

One way to solve this would be to look at the `adjustedContentInset` if available and base the calculations on that. It's also possible to extend the `MagazineLayoutItemWidthMode` to have different options as to whether the safe area should be respected or not (this could enable respecting the safe area on a section/item basis although I think that's rarely what you want).

**Comment by bryankeller** [comment]
This is great timing, I literally just noticed this yesterday when I was looking into a different contentInset issue, and decided to double check how `MagazineLayout` handled it. Thanks for filing the issue and getting a fix up!

> One way to solve this would be to look at the adjustedContentInset if available and base the calculations on that

💯


> It's also possible to extend the MagazineLayoutItemWidthMode to have different options as to whether the safe area should be respected or not (this could enable respecting the safe area on a section/item basis although I think that's rarely what you want).

I agree this is probably not a use-case we'd want to encourage at the API level.
