### ISSUE TITLE
How to add a custom cell with .xib?

### ISSUE THREAD

**Issue by kosicki123** [airbnb/MagazineLayout#19]
Hi, thanks for this nice release but I have the following problem:
I tried to add a custom cell with .xib design file and I cannot get it to work.
If I try to add views programatically like the example, it works like a charm.
Is it possible to add cells like this or just programatically? Should I do something different from the example project?
I can see that my custom cell is rendering, but empty, none of the designed subviews are getting rendered.

Please let me know if I'm doing something wrong.

Thanks!

**Comment by fruitcoder** [comment]
Are your registering the cell class or the xib with the collectionview?

**Comment by kosicki123** [comment]
I was, but in the wrong way.
I had to register it like this:
collectionView.register(UINib(nibName: "TestCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: TestCollectionViewCell.description())
instead of:
collectionView.register(TestCollectionViewCell.self, forCellWithReuseIdentifier: TestCollectionViewCell.description())

That was my mistake, thanks for the tip @fruitcoder.

Problem solved, thanks!
