### ISSUE TITLE
does it support image?

### ISSUE THREAD

**Issue by chengjingfeng** [airbnb/MagazineLayout#20]
does it support to use image with MagazineLayout?

**Comment by bryankeller** [comment]
Hi @chengjingfeng, yes, `MagazineLayout` only handles the layout of elements, it doesn't care what each element contains. You can subclass `MagazineLayoutCollectionViewCell` and add a `UIImageView` if you would like.

https://developer.apple.com/documentation/uikit/uicollectionviewlayout explains a bit more about the layout's role.

**Comment by chengjingfeng** [comment]
thanks @bryankeller
