### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by evil159** [airbnb/MagazineLayout#25]
Is there a chance that the library get iOS 9 support? There seems to be some iOS 9-specific comments in the code, so there was certainly an intention to make it work there. What was the obstacle there?

**Comment by internalG** [comment]
give ios 8 a chance too😑

**Comment by bryankeller** [comment]
I totally understand the desire for supporting old versions of iOS, but unfortunately, we've found `UICollectionView`, particularly with self-sizing cells, to be very bugging before iOS 10. We've also confirmed with UIKit engineers that iOS 10 made many changes to collection view, which might explain why it got more stable.

In short, there's not an interest by the maintainers of this project to support versions of iOS that we know are both old and buggy when it comes to collection view. If you really need to support iOS 9 and earlier, I would encourage you to fork and modify `MagazineLayout`.

----

And for what it's worth, Airbnb is a pretty popular app, and we left iOS 9 a while back. Perhaps you can too? 🙂

**Comment by evil159** [comment]
Yeah, that's what I ended up doing(forking the library), it seems to work ok. I completely understand your point, hopefully we also can drop iOS 9 support soon. 👍
