### ISSUE TITLE
reload data layout been change

### ISSUE THREAD

**Issue by chengjingfeng** [airbnb/MagazineLayout#26]
Hi there,
I got a bug: when reload data, layout has been change, it should be same after reload data

![wechatimg77](https://user-images.githubusercontent.com/8434766/52768250-f44d9280-3067-11e9-9fd9-c0f52166e0ae.png)
![wechatimg78](https://user-images.githubusercontent.com/8434766/52768263-fa437380-3067-11e9-8807-d307ec8527fb.png)
![wechatimg79](https://user-images.githubusercontent.com/8434766/52768271-00d1eb00-3068-11e9-90e6-bed4b1d8cff3.png)

I coded with example project by change the cell to different type by code:
struct ItemInfo {

  let type:ItemType
  let sizeMode: MagazineLayoutItemSizeMode
  let text: String
    let attributeString: NSMutableAttributedString
  let color: UIColor

}

func set(_ itemInfo: ItemInfo) {
    //
    label.textColor = .white
    label.numberOfLines = 0
    contentView.addSubview(label)
    
    
    image.translatesAutoresizingMaskIntoConstraints = false
    label.translatesAutoresizingMaskIntoConstraints = false
    
    contentView.addSubview(image)
    
    if itemInfo.type == .type1{
        NSLayoutConstraint.activate([
            image.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 0),
            //button.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -4),
            image.widthAnchor.constraint(equalToConstant: 50),
            image.heightAnchor.constraint(equalToConstant: 50),
            image.topAnchor.constraint(equalTo: contentView.topAnchor),
            //button.bottomAnchor.constraint(equalTo: contentView.bottomAnchor)
            ])
        
        NSLayoutConstraint.activate([
            label.leadingAnchor.constraint(equalTo: image.trailingAnchor, constant: 4),
            label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: 0),
            label.topAnchor.constraint(equalTo: contentView.topAnchor),
            label.bottomAnchor.constraint(equalTo: contentView.bottomAnchor),
            ])
        
    }else{
        NSLayoutConstraint.activate([
            //image.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 0),
            image.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -4),
            image.widthAnchor.constraint(equalToConstant: 50),
            image.heightAnchor.constraint(equalToConstant: 50),
            image.topAnchor.constraint(equalTo: contentView.topAnchor),
            //button.bottomAnchor.constraint(equalTo: contentView.bottomAnchor)
            ])
        
        NSLayoutConstraint.activate([
            label.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 4),
            label.trailingAnchor.constraint(equalTo: image.leadingAnchor, constant: 0),
            label.topAnchor.constraint(equalTo: contentView.topAnchor),
            label.bottomAnchor.constraint(equalTo: contentView.bottomAnchor),
            ])
        
    }
    //
    
    label.text = itemInfo.text
    label.attributedText = itemInfo.attributeString
    contentView.backgroundColor = itemInfo.color
    
  }

**Comment by chengjingfeng** [comment]
could you help me to figure out how to keep the layout the same after reload data?

**Comment by bryankeller** [comment]
@chengjingfeng can you post full sample code? (Upload a ZIP of the project so I can reproduce locally). Thank you.

**Comment by chengjingfeng** [comment]
@bryankeller I found the root cause, it need to deactivate the NSLayoutConstraint when prepareForReuse the cell, I updated the code by:
//imageC1~ImageC4 is the NSLayoutConstraint of UIImageView
//labelC1~labelC4 is the  NSLayoutConstraint of UILabel
NSLayoutConstraint.deactivate([imageC1,imageC2,imageC3,imageC4])
    NSLayoutConstraint.deactivate([labelC1,labelC2,labelC3,labelC4])

now it works well

**Comment by chengjingfeng** [comment]
thank you @bryankeller  :)
