### ISSUE TITLE
Inserted cell is overlayed on top of existing cells

### ISSUE THREAD

**Issue by evil159** [airbnb/MagazineLayout#27]
**Describe the bug**
With quite simple setup(two sections - first one is empty, second has one cell with static height), after inserting an item into the collection view the inserted cell is overlayed over the existing one.

**To Reproduce**
1. Set collection view's `contentInsets` to `.zero` 
2. Setup data source with one empty section(first) and another section with 1 item
3. Insert an item into the first section

**Expected behavior**
Existing cell is pushed down by inserted cell.

**Actual behaviour**
Inserted cell is overlaid on top of existing cell.

**Screenshots**
![magazinelayout_i
[MagazineLayout.zip](https://github.com/airbnb/MagazineLayout/files/2935240/MagazineLayout.zip)
nsert_issue](https://user-images.githubusercontent.com/1478430/53867343-53198280-3ffc-11e9-83f5-3d39c0dd38a3.gif)

**Smartphone (please complete the following information):**
 - iPhone 8 Simulator(iOS 12), iPad(6th generation) Simulator(iOS 12), iPad (6th generation)(iOS 11)

**Additional context**
If collection view's `contentInsets` have any kind of horizontal margins(even `UIEdgeInsets(top: 0, left: 1, bottom: 0, right: 1)`) - it does seems to help. Not sure why this is happening, I modified example app to show the issue. [MagazineLayout.zip](https://github.com/airbnb/MagazineLayout/files/2935240/MagazineLayout.zip)

**Comment by bryankeller** [comment]
@evil159 you've discovered https://openradar.appspot.com/radar?id=5025850143539200 - a `UICollectionView` bug that I discovered and reported to Apple a few months back. It affects flow layout as well.

Perhaps `MagazineLayout` should warn people if batch updates are attempted with 0 horizontal insets. I feel like many people might run into this issue.

**Comment by evil159** [comment]
@bryankeller I think it is a bit different issue, it also reproduces with static cell sizes. In the example provided there are two cells 30 an 60 pixels hight, the heights are defined statically. I tried to investigate it - it does not seem to be an issue with section height calculation - it's all ok there, looks like it is something else.

**Comment by bryankeller** [comment]
Ah yes, this does seem different - the bug that I linked to should only cause incorrect animations, not leave the layout in an incorrect state. I'm digging into this today.

**Comment by bryankeller** [comment]
@evil159 see that PR for more information, and a workaround

**Comment by bryankeller** [comment]
This issue, and the related one from the open radar, is fixed in `v1.2.2`. Thank you for flagging this issue and providing a great repro project @evil159!

**Comment by evil159** [comment]
Nice, thank you so much for looking into it 👍
