### ISSUE TITLE
Add support for sticky section header

### ISSUE THREAD

**Issue by lj110107** [airbnb/MagazineLayout#33]
**Is your feature request related to a problem? Please describe.**
Just like `UICollectoinViewFlowLayout`, when scrolling the collectionView, the section headers will scroll beyond the visible area while the items in this section are still visible. Is it better for `MagazineLayout` to support this sticky section header just like the `UITableView`. 

**Describe the solution you'd like**
Is it possible to add a notion of `enableStickySectionHeader` to `MagazineLayout` or add a new delegate method `shouldStickyHeaderInSectionAtIndex` to control which section should has this ability.

Thanks

**Comment by bryankeller** [comment]
@lj110107 @DomenicBianchi01 I just merged https://github.com/airbnb/MagazineLayout/pull/52. Grab version 1.5.0 to get sticky headers and footers (I call it pinned headers and footers) 🙂
