### ISSUE TITLE
When removing row data, `heightOfTallestItemInCurrentRow` is always zero.

### ISSUE THREAD

**Issue by youkchansim** [airbnb/MagazineLayout#40]
**Describe the bug**
When removing row data that indexInCurrentRow is more bigger than 0, `heightOfTallestItemInCurrentRow` is always 0. 
So if i remove row that is 3 in MagazineLayout Example, layout cause error.

**Screenshots**
<img width="545" alt="스크린샷 2019-05-07 오전 11 31 17" src="https://user-images.githubusercontent.com/20267227/57267608-a753e800-70bb-11e9-8045-cec289d4c5f3.png">

**Comment by bryankeller** [comment]
Thanks again for your contributions @youkchansim! A variation of your PR has been merged and the version has been bumped to 1.4.2 🙂
