### ISSUE TITLE
Size calculated with default height when collection is reloaded.

### ISSUE THREAD

**Issue by GWStuartClift** [airbnb/MagazineLayout#49]
**Describe the bug**
Given a collection of items using `.dynamic` height, calling `reloadData()` causes cells to be re-sized using the default height of `150` and not their actual height.

**To Reproduce**
1. Download project: 
[MagazineLayout.zip](https://github.com/airbnb/MagazineLayout/files/3278435/MagazineLayout.zip) Or visit Gist: [ViewController.swift](https://gist.github.com/GWStuartClift/2579898d32452aa5cc0c7242e78fb5fe) and add into a project
2. Once running, scroll to the bottom and lick on an item
3. See the scroll offset jump

**Expected behavior**
No change in scroll offset

**Screenshots**
N/A - otherwise layout is good.

**Smartphone (please complete the following information):**
 - Device/Simulator: Device and Simulator
 - OS: 9+
 - Version v1.4.5 and possibly earlier

**Additional context**
This does not happen when providing a static height.

**Comment by bryankeller** [comment]
@GWStuartClift thanks for the report! I gave your sample view controller a shot, and I see the jump you're talking about. Here's the problem - 

When you call `reloadData()`, you're telling collection view and the layout to throw out all sizing information. This causes the collection view's `layoutSubviews` to relayout the collection view with estimated heights. For `MagazineLayout`, this `estimatedHeight` is `150`. I replaced MagazineLayout with flow layout (and made `TextCell` subclass `UICollectionViewCell`), and I experienced similar issues.

In general, you shouldn't need to call `reloadData` - especially not when you're already scrolled down in your collection. Can you switch to using batch updates via `performBatchUpdates`? This will yield better performance, and you'll avoid throwing out layout sizing information.

**Comment by GWStuartClift** [comment]
Thank you for the quick response @bryankeller. 

I initially blamed the jump on the fact that sizing the cell at the `estimatedHeight` of `150` was causing constraints to no longer be satisfiable. This was most easily seen when calling `reloadData()` in a real life project. I seem to have lost this in the process of simplifying a reproducible case and ended up blaming `reloadData()` instead which is in fact behaving as you've suggested.

If I apply the below patch to the project and run everything is fine until I begin to scroll and suddenly get the familiar unsatisfiable constraint spam. Should I open a separate issue or am I going wrong somewhere?

```diff
diff --git a/MagazineLayoutRepro/ViewController.swift b/MagazineLayoutRepro/ViewController.swift
index ecf53fe..38fdc54 100644
--- a/MagazineLayoutRepro/ViewController.swift
+++ b/MagazineLayoutRepro/ViewController.swift
@@ -91,6 +91,7 @@ final class TextCell: MagazineLayoutCollectionViewCell {
             label.leadingAnchor.constraint(equalTo: contentView.leadingAnchor),
             label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
             label.bottomAnchor.constraint(equalTo: contentView.bottomAnchor),
+            label.heightAnchor.constraint(equalToConstant: 30)
             ])
     }
 }
```

**Comment by brynbodayle** [comment]
@GWStuartClift Since you're embedding this label in a collection view, the cell should not have a required height. We solve this in the Airbnb app by lowering the constraint priority of the bottomAnchor constraint for the view we're pinning to the cell's edges.

As UICollectionView self-sizes items, the items will first receive their estimatedHeight before receiving their preferred height. Your item's subviews should have a constraint set up that will accept this estimated height.

**Comment by GWStuartClift** [comment]
Righto, that was the conclusion I had come to but it's good to know that it's the accepted solution here.

I'll close this issue, thank you for the discussion.

**Comment by varol** [comment]
we resolved this issue with like this

```
roundedCornerView.snp.makeConstraints {
      $0.top.right.left.equalToSuperview()
      $0.bottom.lessThanOrEqualToSuperview()
}
```

if your stackview height is not correct, you need add any other element to end of your view

**Comment by yavuzaytekin** [comment]
Hello fellows, We resolved this issue with @varol 
We have 2 solutions. You can use which one is good for you.
1) First one is to update layout for 150 height cells. You can put it to base class and it will be solved from base for all cells which has problem. But you have to think that if you have 150 height normally, layout will update to unnecessary twice.
```
open func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        if cell.frame.size.height == 150 {
            DispatchQueue.main.async {
                collectionView.collectionViewLayout.invalidateLayout()
                collectionView.layoutIfNeeded()
            }
        }
    }
```

2) Second one is to calculate to cell height. You have to calculate cell height by hand.
```
class CardIconFreeTextLabelVM: MagazineCellDataType {

    var sizeMode: MagazineLayoutItemSizeMode {
        return MagazineLayoutItemSizeMode(widthMode: .fullWidth(respectsHorizontalInsets: true),
                                          heightMode: .static(height: cellHeight))
    }

    let title: String
    let iconName: String

    var cellHeight: CGFloat = 0

    init(title: String, iconName: String) {
        self.title = title
        self.iconName = iconName

        heightCalculator()
    }

    var diffHash: Int {
        return .zero
    }

    func heightCalculator() {
        let mainInset = UIEdgeInsets(top: 12, left: 12, bottom: 12, right: 12)
        let screenWidth = UIScreen.main.bounds.width

        let iconWidth: CGFloat = 20
        let mainStackViewInset = UIEdgeInsets(top: 12, left: 16, bottom: 12, right: 16)
        let mainStackViewSpacing: CGFloat = 4

        var height: CGFloat = mainStackViewInset.top + mainStackViewInset.bottom
        height += title.height(withConstrainedWidth: screenWidth - (mainInset.left + mainInset.right + mainStackViewInset.left + mainStackViewInset.right + iconWidth + mainStackViewSpacing), font: TextStyle.paragraphBody2.font)

        cellHeight = height
    }

    func configurator() -> CellConfigurator {
        return CardIconFreeTextLabelConfigurator(item: self)
    }
}
```
```
extension String {
    func height(withConstrainedWidth width: CGFloat, font: UIFont, numberOfLines: Int = 0) -> CGFloat {
        let label =  UILabel(frame: CGRect(x: 0, y: 0, width: width, height: .greatestFiniteMagnitude))
        label.numberOfLines = numberOfLines
        label.text = self
        label.font = font
        label.sizeToFit()
        
        return label.frame.height
    }
}
```
