### ISSUE TITLE
Add Swift PM support 📦

### ISSUE THREAD

**Issue by slashmo** [airbnb/MagazineLayout#55]
**Is your feature request related to a problem? Please describe.**
When setting up a new project I wanted to add `MagazineLayout` via the new Swift PM integration in Xcode 11. This was not possible because this repository lacks a `Package.swift`.
> https://github.com/airbnb/MagazineLayout has no Package.swift manifest for version 1.5.0

Because of this I had to use Cocoapods/Carthage.

**Describe the solution you'd like**
I'd like for `MagazineLayout` to have a `Package.swift` file so that Xcode picks it up as a Swift package.

**Comment by slashmo** [comment]
I just saw that there's already a PR (#53) which implements this, sorry for the duplication. I'm considering this issue resolved once the PR get's merged.

**Comment by bryankeller** [comment]
https://github.com/airbnb/MagazineLayout/pull/53 is merged, closing!
