### ISSUE TITLE
Refresh Control Causes Sticky Header to Stay at Incorrect Position

### ISSUE THREAD

**Issue by ChengmingLu** [airbnb/MagazineLayout#61]
**Describe the bug**
If a `refreshcontrol` is added to the `collectionView`, pulling to refresh will cause the sticky header to pin to incorrect position, instead of top of the screen

**To Reproduce**
1. Go to `MagazineLayoutExample`
2. Go to `ViewController.swift` 
3. Inside `viewDidLoad()`, add `collectionView.refreshControl = .init()`
3. Run the project and pull to refresh, then scroll down
4. You will see the same behavior as shown in the attached gif

**Expected behavior**
The sticky header is expected to pin to the top even when the refresh control is active

**Screenshots**
![fdg](https://user-images.githubusercontent.com/14969440/69457588-63fd5600-0d3b-11ea-9078-4eeb1d8ae514.gif)

**Smartphone**
 - Simulator: iPhone 8 Plus
 - OS: 13.2.2
 - Version: Latest (1.5.2)

**Comment by bryankeller** [comment]
Thanks for reporting this! I've created an alternate fix in #65 that fixes the root of the bug.
