### ISSUE TITLE
Scrolling to item when using dynamic cell height

### ISSUE THREAD

**Issue by okycelt** [airbnb/MagazineLayout#68]
**Describe the bug**
`UICollectionView.scrollToItem(at:at:animated:)` doesn't scroll to the correct position when using dynamic cell height. When using static cell height, it scrolls to the correct position. Sample project [here](https://github.com/okycelt/magazine-scroll-bug-sample).

**To Reproduce**
1. Setup collection view with one cell type
2. Call `collectionView.scrollToItem(at: indexPath, at: .centeredVertically, animated: animated)`
3. Cell at `indexPath` is not centered vertically, but ends up somewhere in the top half of the collection view. See the attached screenshot where **Cell 27** should be centered vertically.

**Expected behavior**
Cell is centered vertically in the collection view.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/26062845/74321733-c0fa2c80-4dbd-11ea-862b-66bf41b718d0.png)

**Smartphone:**
 - iPhone 8 (device), iPhone 11 Pro (simulator)
 - iOS 13.3.1

**Comment by bryankeller** [comment]
Unfortunately, this is a collection view bug and there's nothing we can do in the layout to prevent this kind of issue http://www.openradar.me/radar?id=4941062833438720

Please dupe the radar if you'd like Apple to fix it. Sorry I don't have better news :(
