### ISSUE TITLE
UIKit layout issues with square collection cells

### ISSUE THREAD

**Issue by kacper1703** [airbnb/MagazineLayout#70]
**Describe the bug**
I have a collection view that has a fractional width relative to the View Controller width. 0.4 in Compact size class and 0.3 in Regular. I want my cells to be square in the collection view.

My cell is a Xib with a container view, pinned to the edges of the cell, with 1:1 aspect ratio constraint. 

**Setup code**

```swift
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout,
                        sizeModeForItemAt indexPath: IndexPath) -> MagazineLayoutItemSizeMode {
        switch collectionView.traitCollection.horizontalSizeClass {
        case .compact:
            return MagazineLayoutItemSizeMode(widthMode: .fullWidth(respectsHorizontalInsets: true),
                                              heightMode: .dynamic)
        case .regular:
            return MagazineLayoutItemSizeMode(widthMode: .halfWidth, heightMode: .dynamicAndStretchToTallestItemInRow)
        case .unspecified:
            preconditionFailure()
        @unknown default: //swiftlint:disable:this switch_default_case
            preconditionFailure()
        }
    }

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout,
                        insetsForSectionAtIndex index: Int) -> UIEdgeInsets {
        UIEdgeInsets(...) //non-zero
    }

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout,
                        verticalSpacingForElementsInSectionAtIndex index: Int) -> CGFloat {
        10
    }
```

**Expected behavior**
Cells are square in the collection view

**Actual behavior**

UIKit reports unsatisfiable constraints:
```
(
    "<NSLayoutConstraint:0x600003317570 UIView:0x7fe406f6a510.width == UIView:0x7fe406f6a510.height   (active)>",
    "<NSLayoutConstraint:0x600003315d60 UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide'.bottom == UIView:0x7fe406f6a510.bottom + 3   (active)>",
    "<NSLayoutConstraint:0x600003331bd0 UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide'.trailing == UIView:0x7fe406f6a510.trailing + 3   (active)>",
    "<NSLayoutConstraint:0x600003333250 UIView:0x7fe406f6a510.leading == UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide'.leading + 3   (active)>",
    "<NSLayoutConstraint:0x600003333890 UIView:0x7fe406f6a510.top == UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide'.top + 3   (active)>",
    "<NSLayoutConstraint:0x600003377480 'UIView-Encapsulated-Layout-Height' SquareCollectionCell.height == 150   (active, names: SquareCollectionCell:0x7fe406f6a100 )>",
    "<NSLayoutConstraint:0x600003376080 'UIView-Encapsulated-Layout-Width' SquareCollectionCell.width == 202   (active, names: SquareCollectionCell:0x7fe406f6a100 )>",
    "<NSLayoutConstraint:0x600003321180 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: SquareCollectionCell:0x7fe406f6a100, '|':SquareCollectionCell:0x7fe406f6a100 )>",
    "<NSLayoutConstraint:0x60000331b9d0 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: SquareCollectionCell:0x7fe406f6a100, '|':SquareCollectionCell:0x7fe406f6a100 )>",
    "<NSLayoutConstraint:0x600003333b10 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: SquareCollectionCell:0x7fe406f6a100, '|':SquareCollectionCell:0x7fe406f6a100 )>",
    "<NSLayoutConstraint:0x6000033143c0 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x6000029bd340'UIViewSafeAreaLayoutGuide']   (active, names: SquareCollectionCell:0x7fe406f6a100, '|':SquareCollectionCell:0x7fe406f6a100 )>"
)
```

**Environment:**
 - Device/Simulator: iPad Pro 11 inch
 - OS: 13.3
 - SDK: 1.5.5

**Comment by kacper1703** [comment]
Attaching demo project:
[SquareCellTest.zip](https://github.com/airbnb/MagazineLayout/files/4380682/SquareCellTest.zip)

**Comment by kacper1703** [comment]
@bryankeller could you please have a look? The issue is rather urgent.

**Comment by bryankeller** [comment]
@kacper1703 you need to make your aspect ratio constraint have a lower priority. Since sizing is done by the collection view, your cell needs to respect the size that the collection view determined for your cell. If you have a `.required` aspect ratio constraint, then the collection view is going to break constraints to make the layout resolve correctly.

In your xib, change the aspect ratio constraint to be `.defaultLow` (250).

<img width="643" alt="Screen Shot 2020-03-26 at 2 45 19 AM" src="https://user-images.githubusercontent.com/746571/77632879-d6f62380-6f0b-11ea-806f-594976b1e122.png">


You might also want to consider subclassing `MagazineLayoutCollectionViewCell`, which works around some UIKit bugs.

**Comment by kacper1703** [comment]
Thanks, setting the cell to subclass `MagazineLayoutCollectionViewCell` seems to have worked. Changing the constraint priority to 999 was enough.

But, I encountered another problem in my app - occasionally I get a crash after **tapping the cell**:
```
Fatal error: `layoutAttributes` must be an instance of `MagazineLayoutCollectionViewLayoutAttributes`
```
MagazineLayoutCollectionViewCell.swift, line 47

I say "occasionally" because I use the same viewController with different datasources for cells (they all return the same cell class), and for some cells it crashes. 

Any idea what may cause this?

**Comment by kacper1703** [comment]
Found the crash issue! The same cell was used in another Collection View (not using MagazineLayout) that was being created after tapping the cell. 

Thank you @bryankeller for help with the cell layout issue, I will fix the crash on my own now.
