### ISSUE TITLE
cell height equal with width

### ISSUE THREAD

**Issue by injap2017** [airbnb/MagazineLayout#72]
I tried to create a cell which has fractional width (1/3), and height equal with width. how can I reach it?

**Comment by lby1992** [comment]
@injap2017 I think you can have a try to use the `aspect ratio` of AutoLayout.

**Comment by bryankeller** [comment]
@lby1992 that's correct. Give your component an aspect ratio constraint and a .dynamic height mode in the MagazineLayout delegate. It will self-size to have the same height as the width then 🙂
