### ISSUE TITLE
`layoutAttributesForItem(at:)` crashes when given an empty index path

### ISSUE THREAD

**Issue by maxwellainatchi** [airbnb/MagazineLayout#76]
**Describe the bug**
`layoutAttributesForItem(at:)` crashes when given an empty index path

**To Reproduce**
1. Call `layout.layoutAttributesForItem(at: IndexPath())`

**Expected behavior**
~~Expected it to be treated as `IndexPath(item: 0, section: 0)`, mirroring the `UICollectionViewFlowLayout` behavior~~
Edit: just found a difference. `IndexPath()` returns the first header, while `IndexPath(item: 0, section: 0)` returns the first cell

**Smartphone (please complete the following information):**
 - Device/Simulator: iPad Mini 2nd gen
 - OS: iOS 13.3.1
 - Version [e.g. 22]: 1.6.0

**Additional context**
Note that although common usage (especially with `UICollectionView`s) is that all `IndexPath`s have 2 items, they actually can have any number of items. `row`, `item`, and `section` are just convenience accessors/initializers that assume there are 2 items in the `IndexPath`, which may not be the case

This was in our existing (non-`MagazineLayout`) code, used to scroll to top

**Comment by bryankeller** [comment]
Interesting! I can get this fixed soon. Thanks for the bug report.

**Comment by bryankeller** [comment]
@maxwellainatchi 

> Edit: just found a difference. IndexPath() returns the first header, while IndexPath(item: 0, section: 0) returns the first cell

I don't understand this. If you're calling `layoutAttributesForItem(at:)`, that should *never* return header layout attributes. You should have to call `layoutAttributesForSupplementaryView(ofKind:at:)` to get header attributes

**Comment by bryankeller** [comment]
I also noticed the documentation says that the `init(item:section:)` initializer is for use with `UICollectionView`. It seems like you should be using this regardless of whatever weird quirks / workarounds flow layout has. Is there a reason you're passing in an empty index path? At a minimum, that seems difficult to understand for anyone reading your code - it sounds like even you're discovering new / undocumented quirks with it even now based on your post edit 😜

**Comment by maxwellainatchi** [comment]
It was code that I hadn't written - I was trying to maintain compatibility with our existing code to make MagazineLayout as much of a drop-in replacement as possible. 

I haven't confirmed that it's returning the header layout attributes, I was assuming that was what it was doing because it was returning the top position, but now I suspect it's just returning zeroed attributes.

There's a few ways to work around this so it's not a big deal for me, but I wanted to mention it as an issue since it crashes instead of handling it like `UICollectionViewFlowLayout`. I agree that it's not the ideal case - it took me a little while to even discover that `IndexPath()` was the issue, as I assumed (like you did) that it was the same thing as `IndexPath(item:section:)`.

**Comment by bryankeller** [comment]
Thanks again for the report @maxwellainatchi - collection view is always a mystery with its behavior, and I don't think I would have found this quirk without your report!

Version 1.6.1 (latest tag as of right now) has the changes 😄

**Comment by maxwellainatchi** [comment]
Thanks for the update! Unfortunate that CollectionView even has this behavior to begin with, let alone that we were relying on it, but I appreciate the help.
