### ISSUE TITLE
Animating header resize

### ISSUE THREAD

**Issue by markturnip** [airbnb/MagazineLayout#78]
What's the appropriate way to animate the resize of a header?

I'm currently trying using:
```swift
UIView.animate(withDuration: 0.3) {
  collectionView?.collectionViewLayout.invalidateLayout()
}
```

**Comment by bryankeller** [comment]
@markturnip I'm not sure if that's supported in collection view. I've found that headers seem to be jumpier / animate differently from items, which is unfortunate.

What size mode are you using for the header? `.static` or `.dynamic`? If you could post a sample project / gif that would be helpful!

**Comment by markturnip** [comment]
Using dynamic height header. 
```swift
.visible(heightMode: .dynamic)
```

I'd like to put an example project together to demonstrate. But here's a gif for now:
<img width=320 src=https://d.pr/i/IezcnS.gif>

**Comment by markturnip** [comment]
I think I've managed to get it to work using:
```swift
UIView.animate(withDuration: 0.2) {
  collectionView?.collectionViewLayout.invalidateLayout()
  collectionView?.layoutIfNeeded()
}
```
perhaps isn't most elegant solution?

**Comment by bryankeller** [comment]
@markturnip does that fix it? I'll close out until I hear otherwise. I do think that in general, animating header size changes is something collection view does not handle well. Even the insert / delete animations are kind of glitchy.

I think the best workaround is to just use a cell, or if what you're doing by manually calling `layoutIfNeeded` works, then that seems reasonable!

**Comment by markst** [comment]
if anyone winds up here curious as to implicit header animations when resizing, this might produce a more appealing effect:

```swift
extension OnAirHeader {
  override func action(for layer: CALayer, forKey event: String) -> CAAction? {
    // Disable dodgey animatin
    if event == "opacity" { return nil }
    return super.action(for: layer, forKey: event)
  }
}
```
