### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by YKV** [airbnb/MagazineLayout#95]
**Describe the solution you'd like**
SPM support

**Additional context**
Moving forward SPM support is preferable

**Comment by bryankeller** [comment]
This is already supported. I just tried it out in a new test project:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/746571/133842997-7a49527e-ba2a-49c5-87c6-9ba748117d33.png">

<img width="271" alt="image" src="https://user-images.githubusercontent.com/746571/133843011-87bfffe5-11b7-4af8-90ba-4497e5220e28.png">

Is something not working for you? If so, please reopen this issue. Closing for now.
